name: Manually triggered build and push

on:
  workflow_dispatch:
    inputs:
      dnscrypt-proxy-release:
        description: 'DNSCrypt Proxy Release'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_REPOSITORY }}
          labels: |
            org.opencontainers.image.description='DNS proxy with support for encrypted DNS protocols'
            org.opencontainers.image.version=${{ github.event.inputs.dnscrypt-proxy-release }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_REPOSITORY }}:${{ github.event.inputs.dnscrypt-proxy-release }}
            ${{ secrets.DOCKERHUB_REPOSITORY }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            DNSCRYPT_RELEASE=${{ github.event.inputs.dnscrypt-proxy-release }}
          platforms: linux/amd64,linux/arm64/v8
